# Numpy基础知识点

## 导入Numpy

In [1]:
import numpy as np

## Numpy数组

先建立一个Python数组，然后转化为Numpy专有数组,并查看其数据类型。

NumPy最重要的一个特点就是其N维数组对象（即ndarray），该对象是一个快速而灵活的大数据集容器。

In [5]:
list_a = [1, 2, 3, 4, 5]
list_a

[1, 2, 3, 4, 5]

In [8]:
ndarray_a = np.array(list_a)
ndarray_a

array([1, 2, 3, 4, 5])

In [9]:
print(type(ndarray_a))

<class 'numpy.ndarray'>


## 数组运算

数组的“加减乘除”。

In [11]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [12]:
x + y

array([3., 6., 9.])

In [13]:
x - y

array([-1., -2., -3.])

In [14]:
x * y

array([ 2.,  8., 18.])

In [15]:
x / y

array([0.5, 0.5, 0.5])

In [17]:
x / 2.0

array([0.5, 1. , 1.5])

## 多维数组（矩阵）

### 生成矩阵

- 生成一个2\*2的矩阵
- 查看矩阵的形状
- 查看矩阵的数据类型

In [18]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [21]:
A.shape

(2, 2)

In [23]:
A.dtype

dtype('int32')

### 矩阵的加法和乘法

In [24]:
B = np.array([[3, 0],[0, 6]])
B

array([[3, 0],
       [0, 6]])

In [25]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [26]:
A * B

array([[ 3,  0],
       [ 0, 24]])

### 矩阵的广播

不同形状的数组在一定情况下也可以进行运算

In [29]:
A * 10

array([[10, 20],
       [30, 40]])

In [27]:
C = np.array([10, 20])
C

array([10, 20])

In [28]:
A * C 

array([[10, 40],
       [30, 80]])

这里称作为矩阵的广播，标量10和向量(10, 20)都被扩展到了2\*2的形状，让运算可以顺利执行。

### 访问矩阵元素

对矩阵中特定行、特定列，或者特定元素的访问。

使用 

```Python
np.random.randint(low, high=None, size=None, dtype='l')
```

- 生成一个5\*5的随机整数矩阵

  其中low表示下限（包括），high表示上限（不包括），size表示矩阵的形状，dtype表示数据类型，默认为np.int64。

In [41]:
F = np.random.randint(0, 10, size=(5, 5))
F

array([[0, 0, 0, 1, 8],
       [8, 3, 4, 4, 8],
       [2, 9, 9, 6, 5],
       [7, 4, 1, 6, 2],
       [8, 5, 1, 8, 5]])

- 第i行

In [42]:
F[0]  # 第一行，注意是从0开始

array([0, 0, 0, 1, 8])

- 第j列

In [43]:
F[:, 0]  # 第一列，其中 ： 表示全选

array([0, 8, 2, 7, 8])

- 特定元素选择

In [50]:
# 矩阵第三行第二列的元素的两种选择方法
print(F[2, 1])
print(F[2][1])

9
9


### 矩阵操作与计算

#### 2D矩阵的转置

注意：n维矩阵则需要添加参数，详情参见[numpy.ndarray.transpose](https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.html)

In [64]:
F = np.matrix(F)

In [65]:
print("原矩阵F：")
print("")
print(F)
print("")

print("转置方法一：")
print("")
print(F.T)
print("")

print("转置方法二：")
print("")
print(F.transpose())

原矩阵F：

[[0 0 0 1 8]
 [8 3 4 4 8]
 [2 9 9 6 5]
 [7 4 1 6 2]
 [8 5 1 8 5]]

转置方法一：

[[0 8 2 7 8]
 [0 3 9 4 5]
 [0 4 9 1 1]
 [1 4 6 6 8]
 [8 8 5 2 5]]

转置方法二：

[[0 8 2 7 8]
 [0 3 9 4 5]
 [0 4 9 1 1]
 [1 4 6 6 8]
 [8 8 5 2 5]]


#### 矩阵求逆

In [68]:
M = np.array([[1., 2.], [3., 4.]])
M = np.matrix(M)

In [78]:
print("原矩阵M：")
print("")
print(M)
print("")

print("求逆方法一：")
print("")
print(M.I)
print("")

print("求逆方法二：")
print("")
print(np.linalg.inv(M))

原矩阵M：

[[1. 2.]
 [3. 4.]]

求逆方法一：

[[-2.   1. ]
 [ 1.5 -0.5]]

求逆方法二：

[[-2.   1. ]
 [ 1.5 -0.5]]


验证：M \* M.I 是否等于E ？

可以看到，由于计算精度的原因，不是一个完美的E矩阵。

In [74]:
result = M * M.I
result

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

我们在这里对打印精度做一个设置，可以避免这个问题，参见[numpy.set_printoptions](https://numpy.org/devdocs/reference/generated/numpy.set_printoptions.html)。

In [80]:
np.set_printoptions(suppress=True)
result

matrix([[1., 0.],
        [0., 1.]])

#### 矩阵的迹

矩阵的迹（trace）就是矩阵的主对角线元素之和。

In [81]:
F

matrix([[0, 0, 0, 1, 8],
        [8, 3, 4, 4, 8],
        [2, 9, 9, 6, 5],
        [7, 4, 1, 6, 2],
        [8, 5, 1, 8, 5]])

In [82]:
F.trace()

matrix([[23]])

#### 矩阵的秩

一个矩阵A的列秩是A的线性独立的纵列的极大数，通常表示为r(A)，rk(A)或rank A。

In [84]:
A = np.eye(4)  # 建立一个单位矩阵
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.linalg.matrix_rank(A)

4

#### 矩阵的特征值

$$
\left[
 \begin{matrix}
   -1 & 2 & 2\\
   2 & -1 & 2\\
   2 & -2 & 1
  \end{matrix} 
\right]
$$

In [95]:
B = np.array([[-1, 2, 2], 
              [2, -1, -2],
              [2, -2, -1]])
B = np.matrix(B)
B

matrix([[-1,  2,  2],
        [ 2, -1, -2],
        [ 2, -2, -1]])

In [97]:
w, v = np.linalg.eig(B)
w

array([ 1., -5.,  1.])