# 矩阵的分解

作者：杨岱川

时间：2020年2月

最新编辑：2020年5月

github：https://github.com/DrDavidS/basic_Machine_Learning

开源协议：[MIT](https://github.com/DrDavidS/basic_Machine_Learning/blob/master/LICENSE)

## 矩阵的奇异值分解

对于任一  $m \times n$ 矩阵 $A$，可以进行 SVD 分解，如下：

$$\large A_{m\times n} = U_{m\times m}D_{m\times n}V^T_{n \times n}$$

其中，矩阵 $U$ 的每一个列向量是左奇异向量，对应 $AA^T$ 的特征向量，矩阵 $V$ 的每一个列向量（也就是矩阵 $V^T$ 的每一个行向量）是右奇异向量，对应 $A^TA$ 的特征向量。

矩阵 $D$ 只有在主对角线上存在非零元素，这些元素是 $AA^T$ 的特征值的算数平方根，也是 $A^TA$ 的特征值的算数平方根，称为矩阵 $A$ 的奇异值。

Python中的Numpy库有SVD分解方法。

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,2,3,4],[5,6,7,8]])

print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
u, d, vt = np.linalg.svd(A)

In [4]:
print(u)

[[-0.37616823 -0.92655138]
 [-0.92655138  0.37616823]]


In [5]:
print(d)

[14.22740741  1.25732984]


In [6]:
print(vt)

[[-0.35206169 -0.44362578 -0.53518987 -0.62675396]
 [ 0.75898127  0.3212416  -0.11649807 -0.55423774]
 [-0.40008743  0.25463292  0.69099646 -0.54554195]
 [-0.37407225  0.79697056 -0.47172438  0.04882607]]
